# Generated by Django 4.2.20 on 2025-04-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined name or title for the document.', max_length=200)),
                ('file', models.FileField(help_text='The uploaded document file.', upload_to='documents/%Y/%m/')),
                ('category', models.CharField(choices=[('MD', 'Medical'), ('ID', 'Identity'), ('FN', 'Financial'), ('LG', 'Legal'), ('AG', 'Agreement'), ('OT', 'Other')], default='OT', help_text='Category of the document.', max_length=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(help_text='The family this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.family')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
